export const prompts = [
    'Best song for a summer road trip',
    'Best late-night driving song',
    'Best feel-good song',
    'Best song to cry to alone',
    'Best song to motivate you',
    'Best hype song before a big event',
    'Best song to fall asleep to',
    'Best song to blast at full volume',
    'Best song to pre-game to',
    'Best song for a first date',
    'Best song to play at a wedding',
    'Best song for a breakup',
    'Best song to play at a house party',
    'Best song to play at a family gathering',
    'Best song for a gym workout',
    'Best song to sing in the shower',
    'Best song for a rainy day',
    'Best song for a snowy winter night',
    'Best song for a beach day',
    'Best song for a fall evening',
    'Best song to play on a hot summer night',
    'Best 2000s throwback song',
    'Best 90s R&B song',
    'Best pop-punk anthem',
    'Best hip-hop banger of all time',
    'Best song that never gets old',
    'Best underrated song',
    'Best song from a movie soundtrack',
    'Best song to play in space',
    'Best song to start a mosh pit',
    'Best song to play in a zombie apocalypse',
    'Best song that makes you feel like a main character',
    'Best song that should be illegal to skip',
    'Best song that describes your life',
    'Best song to wake up to',
    'Best song to end the night with',
    'Best song for a road rage moment',
    'Best song that gives you chills',
    'Best song to confess your love to someone',
    'Best song to play at a festival',
    'Best song to listen to while stargazing',
    'Best song that always makes you smile',
    'Best song with the best bass drop',
    'Best song for a nostalgia trip',
    'Best song to play on a rainy Sunday',
    'Best song that instantly hypes you up',
    'Best song to scream at the top of your lungs',
    'Best song that makes you feel unstoppable',
];
